### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by mpounsett** [mpounsett/nagiosplugin#10]
**[Original report](https://bitbucket.org/flyingcircus/nagiosplugin/issue/10) by Arthur Lutz (Bitbucket: [arthurlogilab](https://bitbucket.org/arthurlogilab), GitHub: [arthurlogilab](https://github.com/arthurlogilab)).**

----------------------------------------

A debian package would be nice to deploy these plugins.

We're contemplating contributing the debian packaging.

**Comment by mpounsett** [comment]
**Original comment by Christian Kauhaus (Bitbucket: [ckauhaus](https://bitbucket.org/ckauhaus), GitHub: [ckauhaus](https://github.com/ckauhaus)).**

----------------------------------------

There have been initiatives to provide Debian packaging in the past IIRC, but I'm not sure how far it went. But feel free to provide a debian/rules file and send a pull request so that we can integrate it into the main repo.

**Comment by mpounsett** [comment]
**Original comment by Christian Kauhaus (Bitbucket: [ckauhaus](https://bitbucket.org/ckauhaus), GitHub: [ckauhaus](https://github.com/ckauhaus)).**

----------------------------------------

I'd really appreciate a short description of how to build your own .deb (probably at the end of HACKING.txt).

Which steps must be done to reflect a new version in the Debian packaging stuff? I'm planning on releasing more frequently in the future, so it would be nice to include that into the packaging pipeline.

**Comment by mpounsett** [comment]
**Original comment by Arthur Lutz (Bitbucket: [arthurlogilab](https://bitbucket.org/arthurlogilab), GitHub: [arthurlogilab](https://github.com/arthurlogilab)).**

----------------------------------------

There are too many ways to build debian packages for me to know which one suits your workflow. For the package I've generated for our internal backports (for wheezy) I used "sbuild -A -d wheezy -s" (but this is on a "builder" server that probably has some specific setup).

I'm far from being the expert on building debian packages in my company. I'll ask one my colleagues to see if he has a recommendation.

**Comment by mpounsett** [comment]
**Original comment by Christian Kauhaus (Bitbucket: [ckauhaus](https://bitbucket.org/ckauhaus), GitHub: [ckauhaus](https://github.com/ckauhaus)).**

----------------------------------------

I see the problem. Just any (preferably) short sequence of steps that will produce a locally-built .deb would be ok. I'd like to include that into our CI pipeline so that nobody accidentally breaks the packaging.

**Comment by mpounsett** [comment]
It looks like Debian has added `nagiosplugin` to the main distribution since the issue was originally opened.  Does this meet the needs of the original request, or is there still work to be done here?

**Comment by mpounsett** [comment]
@arthurlogilab, it looks like Debian has added `nagiosplugin` to the main distribution since this issue was originally opened.  Does that meet the needs of the original request, or is there still work here to be done?

**Comment by arthurzenika** [comment]
@mpounsett I think we can say this is fixed, thanks !

**Comment by mpounsett** [comment]
Okay, thanks.  Marking this closed then.
