### ISSUE TITLE
Logged messages appear after the summary

### ISSUE THREAD

**Issue by mpounsett** [mpounsett/nagiosplugin#19]
**[Original report](https://bitbucket.org/flyingcircus/nagiosplugin/issue/19) by Louis Sautier (Bitbucket: [sbraz](https://bitbucket.org/sbraz), GitHub: [sbraz](https://github.com/sbraz)).**

----------------------------------------

Hello,

I’m using the built-in logger to display additional messages based on verbosity but I noticed that they are displayed after the probe function is done running, not in real time. This is a bit confusing because in case of errors, the verbose messages appear after the summary, could this behaviour be changed?

**Comment by mpounsett** [comment]
This seems to be due to the fact that the Runtime object is using a StringIO object for the logging StreamHandler, which is attached to an Output object, which is handling both logging output and result output.  Instead of building the output as each event happens, the Output object assembles it all at once at the end, and it puts result output ahead of all the logging.  

I can see how this has some utility, despite being a bit counterintuitive.  For one thing, it keeps a plugin running in verbose mode from violating the Nagios plugin API, so monitoring that is calling the plugin will still work.  

I'm inclined to label this `wontfix` because of the API issue, but I'm open to discussion about it if you're still interested in seeing this change, @sbraz.  Feel free to re-open the issue.

**Comment by sbraz** [comment]
I'd almost forgotten I'd opened this issue. I can live with the current behaviour, it's just slightly strange :)

**Comment by mpounsett** [comment]
Yeah, a few things got a bit lost when I took over the project.  I'm gradually whittling down these old issues. :)
