### ISSUE TITLE
Default output only shows one failed metric

### ISSUE THREAD

**Issue by davidc** [mpounsett/nagiosplugin#28]
If more than one result is a failure, it currently arbitrarily picks one to display and does not display the others.

I believe it would more useful for the administrator to see in a single message everything that is wrong, rather than fix one thing and then have to wait for the next check to learn that something else was wrong as well.

On top of which the program can't decide which is the most important failed result (and indeed doesn't try, in first_significant)

I know I can write my own Summary class but it seems like it would be sensible to default to showing all problems.

I believe it should at least show all of the problems of the highest severity (but it would probably be okay to omit problems of lower severity). So if something is critical, display all the things that are critical.

Example, here you can see that `queue_size` and `panic_size` are critical, but I won't know about the latter until I fix the former:

```
$ ./check_exim  -qc 0 -pc 0
EXIMQUEUE CRITICAL - queue_size is 2 (outside range 0:0) | oldest_age=600 panic_size=6;;0 queue_size=2;;0 queue_size_bounce=2 queue_size_frozen=2

$ ./check_exim  -pc 0
EXIMQUEUE CRITICAL - panic_size is 6 (outside range 0:0) | oldest_age=600 panic_size=6;;0 queue_size=2 queue_size_bounce=2 queue_size_frozen=2
```

**Comment by mpounsett** [comment]
In principle I think this is a good idea.  I suspect, however, that the original author may have picked a single metric to show for a good reason, such as concerns over output length.  I'll check with the plugin reference and see if there's anything there that we need to be careful about.

**Comment by davidc** [comment]
According to https://nagios-plugins.org/doc/guidelines.html
"Try to keep the output short - probably less that 80 characters"
however you can supply multiple lines (only the first of which is sent in notifications)

So in the example above, it could be something like:

$ ./check_exim  -qc 0 -pc 0
EXIMQUEUE CRITICAL - queue_size and panic_size are critical | oldest_age=600 panic_size=6;;0 queue_size=2;;0 queue_size_bounce=2 queue_size_frozen=2
queue_size is 2 (outside range 0:0) - critical
panic_size is 6 (outside range 0:0) - critical

which gets the most important information into the first line's pager message, and more detail into the full output displayed in the monitoring tool.

**Comment by SwampFalc** [comment]
If you check the current summary code:
- Default will print the "first_significant", which means, for the worst level (critical trumps warning), look at the order in which the resource yields metrics and print the first one. So you can affect that by changing the order in your resource.
- If you run it in verbose mode, each non-ok state will be printed.

So the requested behaviour already exists, it just requires raising the verbosity level high enough, which to me seems perfectly reasonable.

**Comment by mpounsett** [comment]
Seeing no further discussion since the winter, I'm going to close this.  It seems like there is no issue here.
